server:
  port: 8093
  
apikey: thebestsecret
  
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username : sats17
    password : password
  jpa.database-platform: org.hibernate.dialect.H2Dialect